# Site settings
title: "Jakov Perica"
description: "A simple and printable online resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jakov Perica"
resume_title:                   "Software Developer"
resume_contact_email:           "jakov.perica@gmail.com"
resume_contact_telephone:       "0700 91 41 01"
resume_contact_address:         "Lund"
resume_header_contact_info: "0700 91 41 01 | jakov.perica@gmail.com"
resume_header_intro: "
<p>I am a software developer who enjoys working in a team, solving problems and building useful things. I am primarily experienced as a Full Stack Web Developer.</p>
<p>I have an MSc in Management and Economics of Innovation and have experience from business oriented roles. I have built a solid business from which I have made a small exit and have worked with startup valuation for a venture fund.</p>
<p>I am interested in contract jobs in the Lund - Malmö area in Sweden.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jakkan"
  resume_twitter_url:           #"http://twitter.com/jglovier"
  resume_dribbble_url:          #"https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jakovperica"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://www.twiddlebit.se"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
